import type { WordOption } from '@draw-guess/shared';

/** 内置中文词库,{词, 分类提示} */
export const WORD_BANK: WordOption[] = [
  // 动物
  { text: '大熊猫', hint: '动物' },
  { text: '长颈鹿', hint: '动物' },
  { text: '孔雀', hint: '动物' },
  { text: '章鱼', hint: '动物' },
  { text: '企鹅', hint: '动物' },
  { text: '蜗牛', hint: '动物' },
  { text: '袋鼠', hint: '动物' },
  { text: '刺猬', hint: '动物' },
  { text: '海马', hint: '动物' },
  { text: '蝴蝶', hint: '动物' },
  { text: '螃蟹', hint: '动物' },
  { text: '恐龙', hint: '动物' },
  // 食物
  { text: '火锅', hint: '食物' },
  { text: '烤串', hint: '食物' },
  { text: '汉堡包', hint: '食物' },
  { text: '寿司', hint: '食物' },
  { text: '冰淇淋', hint: '食物' },
  { text: '棉花糖', hint: '食物' },
  { text: '小笼包', hint: '食物' },
  { text: '螺蛳粉', hint: '食物' },
  { text: '煎饼果子', hint: '食物' },
  { text: '糖葫芦', hint: '食物' },
  // 水果蔬菜
  { text: '西瓜', hint: '水果' },
  { text: '菠萝', hint: '水果' },
  { text: '榴莲', hint: '水果' },
  { text: '葡萄', hint: '水果' },
  { text: '胡萝卜', hint: '蔬菜' },
  { text: '茄子', hint: '蔬菜' },
  { text: '玉米', hint: '蔬菜' },
  // 物品
  { text: '雨伞', hint: '物品' },
  { text: '眼镜', hint: '物品' },
  { text: '手电筒', hint: '物品' },
  { text: '吹风机', hint: '物品' },
  { text: '订书机', hint: '物品' },
  { text: '灭火器', hint: '物品' },
  { text: '望远镜', hint: '物品' },
  { text: '洗衣机', hint: '物品' },
  { text: '电饭煲', hint: '物品' },
  { text: '充电宝', hint: '物品' },
  { text: '牙刷', hint: '物品' },
  { text: '口罩', hint: '物品' },
  { text: '风筝', hint: '物品' },
  { text: '灯笼', hint: '物品' },
  { text: '闹钟', hint: '物品' },
  { text: '路由器', hint: '物品' },
  // 运动
  { text: '篮球', hint: '运动' },
  { text: '羽毛球', hint: '运动' },
  { text: '游泳', hint: '运动' },
  { text: '跳绳', hint: '运动' },
  { text: '瑜伽', hint: '运动' },
  { text: '拔河', hint: '运动' },
  { text: '举重', hint: '运动' },
  { text: '射箭', hint: '运动' },
  { text: '滑雪', hint: '运动' },
  { text: '乒乓球', hint: '运动' },
  // 职业
  { text: '医生', hint: '职业' },
  { text: '消防员', hint: '职业' },
  { text: '宇航员', hint: '职业' },
  { text: '厨师', hint: '职业' },
  { text: '魔术师', hint: '职业' },
  { text: '快递员', hint: '职业' },
  { text: '理发师', hint: '职业' },
  { text: '程序员', hint: '职业' },
  // 动作
  { text: '刷牙', hint: '动作' },
  { text: '洗澡', hint: '动作' },
  { text: '钓鱼', hint: '动作' },
  { text: '打喷嚏', hint: '动作' },
  { text: '倒立', hint: '动作' },
  { text: '照镜子', hint: '动作' },
  { text: '敷面膜', hint: '动作' },
  { text: '晒太阳', hint: '动作' },
  { text: '放鞭炮', hint: '动作' },
  { text: '堆雪人', hint: '动作' },
  // 自然
  { text: '彩虹', hint: '自然' },
  { text: '闪电', hint: '自然' },
  { text: '火山', hint: '自然' },
  { text: '瀑布', hint: '自然' },
  { text: '沙漠', hint: '自然' },
  { text: '月亮', hint: '自然' },
  { text: '流星', hint: '自然' },
  { text: '龙卷风', hint: '自然' },
  // 交通
  { text: '地铁', hint: '交通工具' },
  { text: '热气球', hint: '交通工具' },
  { text: '潜水艇', hint: '交通工具' },
  { text: '摩托车', hint: '交通工具' },
  { text: '直升机', hint: '交通工具' },
  { text: '高铁', hint: '交通工具' },
  { text: '共享单车', hint: '交通工具' },
  // 地点
  { text: '图书馆', hint: '地点' },
  { text: '游乐园', hint: '地点' },
  { text: '菜市场', hint: '地点' },
  { text: '电影院', hint: '地点' },
  { text: '动物园', hint: '地点' },
  { text: '长城', hint: '地点' },
  { text: '天安门', hint: '地点' },
  { text: '埃菲尔铁塔', hint: '地点' },
  // 乐器
  { text: '钢琴', hint: '乐器' },
  { text: '吉他', hint: '乐器' },
  { text: '架子鼓', hint: '乐器' },
  { text: '小提琴', hint: '乐器' },
  { text: '唢呐', hint: '乐器' },
  // 成语
  { text: '画蛇添足', hint: '成语' },
  { text: '井底之蛙', hint: '成语' },
  { text: '守株待兔', hint: '成语' },
  { text: '亡羊补牢', hint: '成语' },
  { text: '狐假虎威', hint: '成语' },
  { text: '对牛弹琴', hint: '成语' },
  { text: '掩耳盗铃', hint: '成语' },
  { text: '闻鸡起舞', hint: '成语' },
  // 影视动漫
  { text: '孙悟空', hint: '影视/动漫角色' },
  { text: '奥特曼', hint: '影视/动漫角色' },
  { text: '皮卡丘', hint: '影视/动漫角色' },
  { text: '哆啦A梦', hint: '影视/动漫角色' },
  { text: '海绵宝宝', hint: '影视/动漫角色' },
  { text: '葫芦娃', hint: '影视/动漫角色' },
  { text: '灰太狼', hint: '影视/动漫角色' },
  { text: '超人', hint: '影视/动漫角色' },
  { text: '蜘蛛侠', hint: '影视/动漫角色' },
  { text: '白雪公主', hint: '影视/动漫角色' },
  // 节日/其他
  { text: '春节', hint: '节日' },
  { text: '中秋节', hint: '节日' },
  { text: '圣诞树', hint: '节日相关' },
  { text: '生日蛋糕', hint: '节日相关' },
  { text: '红包', hint: '节日相关' },
  { text: '婚礼', hint: '活动' },
  { text: '自拍', hint: '日常' },
  { text: '堵车', hint: '日常' },
  { text: '外卖', hint: '日常' },
  { text: '双十一', hint: '日常' },
];
